Fix: various phantom-js related failures
- errors:
```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'webDriver' defined in DefaultAcceptanceTestConfig
```
and:
```
org.openqa.selenium.UnsupportedCommandException: TypeError - undefined is not a function (evaluating '_getTagName(currWindow).toLowerCase()')
```
- This commit resolves these issues by replacing
phantom-js with ChromeDriver, as research has shown that
phantom-js has fallen out of standards and is not maintained
well (see: https://github.com/ariya/phantomjs/issues/15344).
ChromeDriver is now the standard (also what `uaa` repo uses)
- the driver config is based on the existing configs in `uaa`
repo, which has tests of very similar nature as this repo:
https://github.com/cloudfoundry/uaa/blob/d3cbf284ae92fc4cfb6c68f908c479f5e5b22e9e/uaa/src/test/java/org/cloudfoundry/identity/uaa/integration/feature/DefaultIntegrationTestConfig.java#L53

[#182917624]