Attempt fix: phantomjs error
- error:
```
org.openqa.selenium.UnsupportedCommandException: TypeError - undefined is not a function (evaluating '_getTagName(currWindow).toLowerCase()')
```
- according to https://github.com/ariya/phantomjs/issues/14211
we need to upgrade phantomjs
- however, the old source of phantomjsdriver seems not be updated for a
  long time: https://mvnrepository.com/artifact/com.github.detro.ghostdriver/phantomjsdriver
- so trying this source: https://mvnrepository.com/artifact/com.codeborne/phantomjsdriver/1.2.1
and a higer version